volumes:
  prometheus-data0: {}
  prometheus-data1: {}
  grafana-data: {}

services:
  prometheus-0:
    image: prom/prometheus:latest
    container_name: prometheus-0
    ports:
      - '9090:9090'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9090"]
      interval: 60s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./prometheus0.yml:/etc/prometheus/prometheus.yml
      - ./web.yml:/etc/prometheus/web.yml
      - prometheus-data0:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'

  prometheus-1:
    image: prom/prometheus:latest
    container_name: prometheus-1
    ports:
      - '9091:9090'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9090"]
      interval: 60s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./prometheus1.yml:/etc/prometheus/prometheus.yml
      - ./web.yml:/etc/prometheus/web.yml
      - prometheus-data1:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'

  grafana-0:
    image: grafana/grafana:latest
    container_name: grafana-0
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:3000"]
      interval: 60s
      retries: 3
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./certificate-authority/grafana.key:/etc/grafana/ssl/grafana.key:ro
      - ./certificate-authority/grafana.crt:/etc/grafana/ssl/grafana.crt:ro
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/ssl/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/ssl/grafana.key
      
  grafana-1:
    image: grafana/grafana:latest
    container_name: grafana-1
    ports:
      - '3001:3000'
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:3000"]
      interval: 60s
      retries: 3
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./certificate-authority/grafana.key:/etc/grafana/ssl/grafana.key:ro
      - ./certificate-authority/grafana.crt:/etc/grafana/ssl/grafana.crt:ro
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/ssl/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/ssl/grafana.key

  nginx:
    image: nginx:latest
    container_name: grafana-lb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:443"]
      interval: 60s
      retries: 3
    network_mode: host
    pid: host
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificate-authority/grafana.key:/etc/nginx/ssl/grafana.key:ro
      - ./certificate-authority/grafana.crt:/etc/nginx/ssl/grafana.crt:ro
    depends_on:
      - grafana-0
      - grafana-1
