global:
  scrape_interval: 5m

  external_labels:
      cluster: 'monitoring-cluster'
      __replica__: 'prometheus0'


scrape_configs:
  - job_name: 'power-exporter'
    static_configs:
      - targets: ['172.17.0.1:9102']

